version: "3.7"
services:
  backend:
    build: backend
    ports:
      - 8080:8080
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_PASSWORD=mypass
      - MYSQL_USER=myuser
    networks:
      - spring-mysql
  db:
  restart: always
  image: mariadb
  container_name: myapp_db
  environment:
    - MYSQL_USER=myuser
    - MYSQL_PASSWORD=mypass
    - MYSQL_DATABASE=mydb
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  ports:
    - 3306:3306
  networks:
    - spring-mysql
volumes:
  db-data:
# secrets:
#   db-password:
#     file: db/password.txt
networks:
  spring-mysql:
